name: Dubai Real Estate MLOps
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install dagshub
        
      - name: Run Monitoring
        continue-on-error: true 
        run: python src/monitor.py
        
      - name: Run Training & Log to DagsHub
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          # Explicit URI for MLflow to  find the DagsHub
          MLFLOW_TRACKING_URI: https://dagshub.com/N-KATOCH/dubai_real_estate_predictor.mlflow
        run: python src/train.py

      - name: Upload Drift Report to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: dubai-real-estate-reports
          path: reports/data_drift_report.html
